apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mylab
  template:
    metadata:
      labels:
        app: mylab
    spec:
      containers:
        - name: ms-mylab
          image: gabrielgpa/wodpress:1.0.0
          ports:
            - containerPort: 8000
          # env:
          #   - name: MONGO_URL
          #     value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mylab
spec:
  selector:
    app: mylab
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer